const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const { createRequire } = require("node:module");
const test = require("node:test");
const { GROUPS, LANGUAGES, loadCatalogs, loadRetiredKeys, buildOutputs } = require("../tools/build-messages.cjs");

const ROOT = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(ROOT, file), "utf8");
const plain = value => JSON.parse(JSON.stringify(value));
// This explicit list is the scope of the approved retirement, not a generic
// permission to drop baseline entries or any key without a literal reference.
const EXPECTED = Object.freeze({
  binding: "common",
  diagnostics: "common",
  live: "common",
  saved: "common",
  removeFavorite: "favorites",
  moveBookmark: "bookmarks",
  searchResultCount: "search",
  conversationPreview: "time",
  exportFileCitation: "export",
  exportImagePackageFailed: "export",
  exportPlanAssets: "export",
  exportAssets: "export",
});
const retiredNames = Object.keys(EXPECTED).sort();

function catalog(group) {
  return JSON.parse(read("src/messages/catalogs/" + group + ".json"));
}

function messageRuntime() {
  // Generate only in memory. The shipping runtime may not have been refreshed
  // yet, and this contract must never mistake stale generated bytes for source.
  const outputs = buildOutputs();
  const context = vm.createContext({});
  vm.runInContext(outputs.get("src/messages/i18n.js").replace(/^export /gm, "")
    + "\nglobalThis.catalog = STRINGS; globalThis.translate = createTranslator;", context);
  vm.runInContext(read("src/features/export/engine/i18n.js"), context);
  return context;
}

test("the retirement manifest authorizes exactly the audited keys and preserves every historical language hash", () => {
  const manifest = JSON.parse(read("src/messages/retired-keys.json"));
  const entries = loadRetiredKeys();
  const { strings, retiredKeys } = loadCatalogs();
  const baseline = JSON.parse(read("docs/current/BEHAVIOR_BASELINE.json")).stringHashes;
  assert.equal(manifest.schemaVersion, 1);
  assert.deepEqual(entries, manifest.retiredKeys);
  assert.deepEqual(retiredKeys, entries);
  assert.deepEqual(entries.map(entry => entry.key).sort(), retiredNames);
  for (const entry of entries) {
    assert.equal(entry.catalog, EXPECTED[entry.key], entry.key + " keeps its original owner");
    assert.ok(typeof entry.reason === "string" && entry.reason.trim(), entry.key + " has an audit reason");
    assert.deepEqual(Object.keys(entry.beforeHashes).sort(), [...LANGUAGES].sort());
    for (const language of LANGUAGES) {
      assert.match(entry.beforeHashes[language], /^[a-f0-9]{64}$/);
      assert.equal(entry.beforeHashes[language], baseline[language + ":" + entry.key],
        language + ":" + entry.key + " must retain its historical fingerprint");
    }
    // A retired status can legitimately have no semantic replacement. Do not
    // manufacture compatibility aliases for binding/live/saved.
    assert.ok(Array.isArray(entry.replacements));
    assert.equal(new Set(entry.replacements).size, entry.replacements.length);
    for (const replacement of entry.replacements) {
      assert.ok(typeof replacement === "string" && replacement.trim());
      assert.ok(!retiredNames.includes(replacement), replacement + " must remain active");
      for (const language of LANGUAGES) assert.equal(typeof strings[language][replacement], "string");
    }
  }
});

test("retired keys are absent from every source catalog and fresh four-language runtime", () => {
  const { strings } = loadCatalogs();
  const runtime = messageRuntime();
  for (const group of GROUPS) for (const key of retiredNames) {
    assert.equal(Object.hasOwn(catalog(group).messages, key), false, group + ":" + key);
  }
  for (const language of LANGUAGES) for (const key of retiredNames) {
    assert.equal(Object.hasOwn(strings[language], key), false, language + ":" + key);
    assert.equal(Object.hasOwn(runtime.catalog[language], key), false, language + ":" + key);
    // The general translator still keeps its original unknown-key contract;
    // retirement is not a hidden alias or another compatibility lookup.
    assert.equal(runtime.translate(language)(key), key);
  }
});

test("every retired key is rejected if re-registered in either its former or another catalog", () => {
  loadCatalogs(); // Establish that the unmodified catalogs are valid first.
  for (const key of retiredNames) for (const group of GROUPS) {
    const override = catalog(group);
    override.messages[key] = Object.fromEntries(LANGUAGES.map(language => [language, "Regression sentinel"]));
    assert.throws(() => loadCatalogs({ catalogOverrides: { [group]: override } }),
      error => String(error.message).includes(key), group + ":" + key + " must not be registered again");
  }
});

test("page and theme bindings cannot turn retired keys into indirect runtime dependencies", () => {
  loadCatalogs();
  for (const key of retiredNames) for (const [group, field] of [["time", "pageBindings"], ["settings", "themeBindings"]]) {
    const override = catalog(group);
    override[field] = { ...override[field], retirementRegression: key };
    assert.throws(() => loadCatalogs({ catalogOverrides: { [group]: override } }),
      error => String(error.message).includes(key), field + ":" + key + " must fail binding validation");
  }
});

test("export vocabulary snapshots never request retired interface labels", () => {
  const runtime = messageRuntime();
  for (const language of LANGUAGES) {
    const requested = [];
    const translate = runtime.translate(language);
    const messages = runtime.TidyExport.createExportMessages(key => {
      requested.push(key);
      assert.ok(!retiredNames.includes(key), "export snapshot requested " + key);
      assert.ok(Object.hasOwn(runtime.catalog[language], key), "export vocabulary must be registered");
      return translate(key);
    });
    assert.ok(requested.length > 0);
    assert.deepEqual(Object.keys(messages).sort(), [...requested].sort());
    assert.equal(Object.isFrozen(messages), true);
  }
});

test("export error descriptors reject retired non-export keys before invoking a translator", () => {
  const runtime = messageRuntime();
  const api = runtime.TidyExport;
  const fallbacks = ["exportGenerationFailed", "exportPreviewFailed", "exportUnavailable", "exportBatchUnavailable"];
  for (const language of LANGUAGES) for (const key of retiredNames.filter(key => !key.startsWith("export"))) for (const fallback of fallbacks) {
    const requested = [];
    const translate = runtime.translate(language);
    const spy = (messageKey, values) => {
      requested.push(messageKey);
      assert.ok(!retiredNames.includes(messageKey), "retired error key crossed the export boundary");
      return translate(messageKey, values);
    };
    const error = api.exportError(key, { count: 3 });
    assert.deepEqual(plain(api.exportErrorDescriptor(error, spy, fallback)), { key: fallback, values: {} });
    assert.deepEqual(requested, [], "non-export keys are rejected before translation");
    assert.equal(api.exportErrorText(error, spy, fallback), translate(fallback));
    assert.deepEqual(requested, [fallback]);
  }
});

// A retired export-prefixed key is still passed to the normal translator
// boundary; its unknown-key result must fall back, never become UI copy.
test("retired export citation labels fall back instead of displaying raw keys", () => {
  const runtime = messageRuntime(), api = runtime.TidyExport;
  for (const language of LANGUAGES) for (const key of retiredNames.filter(key => key.startsWith("export"))) {
    const translate = runtime.translate(language), fallback = "exportGenerationFailed";
    const error = api.exportError(key, { reference: "turn0search0" });
    assert.deepEqual(plain(api.exportErrorDescriptor(error, translate, fallback)), { key: fallback, values: {} });
    assert.equal(api.exportErrorText(error, translate, fallback), translate(fallback));
  }
});

// Exercise the real source scanner with a read-only filesystem facade. The
// synthetic source exists only in memory; no production file or generated
// artifact is edited and no generic ban is placed on similarly named fields.
function scannedIndex(extraSource = "") {
  const scannerFile = path.join(ROOT, "tools/build-message-index.cjs");
  const injectedFile = path.join(ROOT, "src/features/time/ui/time-view.js");
  const scannerRequire = createRequire(scannerFile);
  const readonlyFs = Object.create(fs);
  readonlyFs.readFileSync = (file, ...args) => {
    const content = fs.readFileSync(file, ...args);
    return path.resolve(String(file)) === injectedFile ? String(content) + extraSource : content;
  };
  readonlyFs.writeFileSync = () => { throw new Error("The retirement scanner test must remain in memory."); };
  readonlyFs.mkdirSync = () => { throw new Error("The retirement scanner test must not create directories."); };
  const localRequire = name => name === "node:fs" ? readonlyFs : scannerRequire(name);
  const module = { exports: {} };
  const context = vm.createContext({ require: localRequire, module, exports: module.exports,
    __dirname: path.dirname(scannerFile), __filename: scannerFile });
  vm.runInContext(read("tools/build-message-index.cjs"), context, { filename: scannerFile });
  const outputs = context.module.exports.buildOutputs();
  return JSON.parse(outputs.get("docs/current/MESSAGE_INDEX.json"));
}

test("the message index flags retired literal translator calls without banning unrelated field names", () => {
  const baseline = scannedIndex();
  for (const key of retiredNames) assert.ok(!baseline.messages.some(entry => entry.key === key));
  const bareFields = "\nconst auditFields = { binding: null, diagnostics: null, live: true, saved: 1, "
    + "removeFavorite() {}, searchResultCount: 2, conversationPreview: null };\n";
  const fieldsOnly = scannedIndex(bareFields);
  assert.deepEqual(fieldsOnly.unknownLiteralCalls, baseline.unknownLiteralCalls,
    "ordinary domain fields are not translation calls");
  const injected = scannedIndex(bareFields + retiredNames.map(key => "t(" + JSON.stringify(key) + ");").join("\n"));
  const unknownRetired = injected.unknownLiteralCalls.filter(call => retiredNames.includes(call.key));
  assert.deepEqual(unknownRetired.map(call => call.key).sort(), retiredNames);
  assert.ok(unknownRetired.every(call => call.source === "src/features/time/ui/time-view.js" && call.callee === "t"));
  assert.equal(injected.unknownLiteralCalls.length, baseline.unknownLiteralCalls.length + retiredNames.length);
});
