/* PDF 生成器：按导出片段顺序排版，嵌入文字、所需字体和图片；不是网页截图。 */
(function (root) {
  'use strict';

  const api = root.TidyExport = root.TidyExport || {};
  // 产品排版参数：纸张尺寸与正文字号均以 pt 为单位（72 pt = 1 英寸），不是 CSS 像素。
  const PAGE_SIZES = Object.freeze({ A4: [595.28, 841.89], Letter: [612, 792] });
  const FONT_SIZES = Object.freeze({ small: 9.5, standard: 10.75, large: 12 });
  const FONT_PATHS = Object.freeze({
    manifest: './vendor/fonts/noto-sans-sc/manifest.json',
    shardBase: './vendor/fonts/noto-sans-sc/',
    fallbackManifest: './vendor/fonts/fallback/manifest.json',
    fallbackBase: './vendor/fonts/fallback/',
    emoji: './vendor/fonts/NotoEmoji-Regular.ttf',
  });
  // These strings are generated by the renderer rather than supplied by the
  // source contract, so include them when choosing offline font shards.
  const PDF_PUNCTUATION = '［］～／：，。！？（）【】《》□ #0123456789-T.Z+';
  const PDF_LABEL_KEYS = Object.freeze([
    'untitled', 'exportDocumentTitle', 'exportBookmarkExcerpt',
    'exportExcerptNotice', 'exportImage', 'exportImageLabel', 'exportImageEmbedFailed',
    'exportAttachment', 'exportUnnamedAttachment', 'exportVisibleProcess', 'exportToolProcess',
    'exportWebProcess', 'exportToolLabel', 'exportQueryLabel', 'exportFinalSources',
    'exportFromGroup', 'exportOpenOriginal',
  ]);
  const HEX = Object.freeze({
    text: '#20242C', muted: '#59616D', accent: '#5969A8',
    process: '#F3F5FA', user: '#F7F8FA', line: '#E3E6EB', white: '#FFFFFF',
  });

  function toRgb(PDFLib, hex) {
    const value = Number.parseInt(hex.slice(1), 16);
    return PDFLib.rgb(((value >> 16) & 255) / 255, ((value >> 8) & 255) / 255, (value & 255) / 255);
  }

  async function loadAsset(path, context) {
    if (typeof context?.assetLoader === 'function') return context.assetLoader(path);
    try { return await api.readExportAsset(path); }
    catch (error) {
      if (error?.code === 'EXPORT_ASSET_HTTP') throw api.exportError('exportPdfAssetFailed', { path });
      throw error;
    }
  }

  // PDF 原生支持 PNG/JPEG。WebP/GIF 在浏览器本地转成 PNG（动图只取首帧），
  // 不上传到转换服务；无损保留 PNG/JPEG 原始字节，避免不必要的重编码。
  async function preparePdfImage(bytes) {
    if (bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47) return { format: 'png', bytes };
    if (bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return { format: 'jpeg', bytes };
    const ascii = (start, end) => String.fromCharCode(...bytes.slice(start, end));
    const mime = ascii(0, 4) === 'RIFF' && ascii(8, 12) === 'WEBP' ? 'image/webp'
      : ['GIF87a', 'GIF89a'].includes(ascii(0, 6)) ? 'image/gif' : '';
    if (!mime || !root.createImageBitmap || !root.OffscreenCanvas) throw new Error('Unsupported PDF image');
    const bitmap = await root.createImageBitmap(new Blob([bytes], { type: mime }));
    try {
      const canvas = new root.OffscreenCanvas(bitmap.width, bitmap.height);
      canvas.getContext('2d').drawImage(bitmap, 0, 0);
      const png = await canvas.convertToBlob({ type: 'image/png' });
      return { format: 'png', bytes: new Uint8Array(await png.arrayBuffer()) };
    } finally { bitmap.close(); }
  }

  function assetJson(bytes) {
    try { return JSON.parse(new TextDecoder().decode(bytes)); }
    catch (error) { throw api.exportError('exportPdfFontsInvalid'); }
  }

  function collectCodePoints(value, output) {
    if (typeof value === 'string') {
      for (const character of value) output.add(character.codePointAt(0));
      return;
    }
    if (Array.isArray(value)) { value.forEach((item) => collectCodePoints(item, output)); return; }
    if (value && typeof value === 'object') Object.values(value).forEach((item) => collectCodePoints(item, output));
  }

  function collectMediumCodePoints(file, context, output) {
    collectCodePoints(PDF_PUNCTUATION, output);
    collectCodePoints(PDF_LABEL_KEYS.map((key) => context.messages[key]), output);
    collectCodePoints(api.resolveRoleNames(context.roleNames), output);
    const collectConversation = (conversation) => {
      collectCodePoints(conversation.title || '', output);
      // Rendered dates may contain localized words absent from the source ISO.
      for (const value of [conversation.createdAt, conversation.updatedAt]) {
        collectCodePoints(context.formatTimestamp ? context.formatTimestamp(value) : value, output);
      }
    };
    const collectMessage = (message, conversation) => {
      collectCodePoints(message.timestamp && context.formatTimestamp ? context.formatTimestamp(message.timestamp) : message.timestamp || '', output);
      for (const segment of message.segments || []) {
        if (segment.type === 'process') collectCodePoints(segment.label || '', output);
        for (const block of segment.blocks || []) {
          if (block.type === 'heading') collectCodePoints(block.text || '', output);
          else if (block.type === 'code') collectCodePoints(block.language || '', output);
          else if (block.type === 'table') collectCodePoints(block.headers || [], output);
          else if (block.type === 'attachment') {
            const resource = (conversation.resources || []).find((item) => item.id === block.resourceId);
            collectCodePoints(resource?.name || '', output);
          }
        }
      }
    };
    if (file.kind === 'conversation') {
      for (const conversation of file.conversations || []) {
        collectConversation(conversation);
        (conversation.messages || []).forEach((message) => collectMessage(message, conversation));
      }
    } else {
      for (const entry of file.bookmarkEntries || []) {
        collectConversation(entry.conversation);
        if (entry.message && entry.conversation) collectMessage(entry.message, entry.conversation);
      }
    }
  }

  function graphemes(value) {
    const text = String(value || '');
    if (typeof Intl?.Segmenter === 'function') {
      return [...new Intl.Segmenter(undefined, { granularity: 'grapheme' }).segment(text)].map((item) => item.segment);
    }
    return [...text];
  }


  async function serializePdf(file, context = {}) {
    const t = (key, values) => api.exportText(context.messages, key, values);
    const PDFLib = root.PDFLib;
    const fontkit = root.fontkit;
    if (!PDFLib || !fontkit) throw api.exportError('exportDependencyNotReady', { name: 'PDF' });
    const { PDFDocument, PDFHexString } = PDFLib;
    // Product-manager tuning point: all document colors live in HEX above.
    const colors = {
      text: toRgb(PDFLib, HEX.text), muted: toRgb(PDFLib, HEX.muted),
      accent: toRgb(PDFLib, HEX.accent), process: toRgb(PDFLib, HEX.process),
      user: toRgb(PDFLib, HEX.user), line: toRgb(PDFLib, HEX.line),
      white: toRgb(PDFLib, HEX.white),
    };
    const pdfOptions = { pageSize: 'A4', orientation: 'portrait', fontSize: 'standard', pageNumbers: true, ...(context.pdf || {}) };
    const options = { timestamps: true, messageNumbers: true, ...(context.options || {}) };
    let pageSize = PAGE_SIZES[pdfOptions.pageSize] || PAGE_SIZES.A4;
    if (pdfOptions.orientation === 'landscape') pageSize = [pageSize[1], pageSize[0]];
    const baseSize = FONT_SIZES[pdfOptions.fontSize] || FONT_SIZES.standard;
    const lineHeight = baseSize * 1.62;
    const marginX = 48;
    const contentWidth = pageSize[0] - marginX * 2;
    const headerY = pageSize[1] - 25;
    const contentTop = pageSize[1] - 51;
    const footerLimit = pdfOptions.pageNumbers ? 40 : 29;
    const warnings = [];
    const pdfDoc = await PDFDocument.create();
    const manifest = assetJson(await loadAsset(FONT_PATHS.manifest, context));
    const fallbackManifest = assetJson(await loadAsset(FONT_PATHS.fallbackManifest, context));
    const emojiBytes = await loadAsset(FONT_PATHS.emoji, context);

    if (manifest?.schema !== 'chatgpt-tidy.pdf-font-shards.v1' || !Array.isArray(manifest.shards) || !manifest.shards.length) {
      throw api.exportError('exportPdfFontsInvalid');
    }
    if (fallbackManifest?.schema !== 'chatgpt-tidy.pdf-font-fallbacks.v1' || !Array.isArray(fallbackManifest.families)) {
      throw api.exportError('exportPdfFontsInvalid');
    }
    const usedCodePoints = new Set();
    collectCodePoints(file, usedCodePoints);
    collectCodePoints(api.resolveRoleNames(context.roleNames), usedCodePoints);
    collectCodePoints(PDF_PUNCTUATION, usedCodePoints);
    collectCodePoints(PDF_LABEL_KEYS.map((key) => context.messages[key]), usedCodePoints);
    const mediumCodePoints = new Set();
    collectMediumCodePoints(file, context, mediumCodePoints);
    mediumCodePoints.forEach((point) => usedCodePoints.add(point));
    const selectShards = (points) => manifest.shards
      .map((shard, index) => ({ ...shard, index }))
      .filter((shard) => [...points].some((point) => point >= shard.start && point <= shard.end));
    const selectedRegularShards = selectShards(usedCodePoints);
    const selectedMediumShards = selectShards(mediumCodePoints);

    // Each checked-in shard is cleaned and compacted by FontTools ahead of
    // release. At runtime we embed only the shards this document needs. The
    // bundled fontkit version cannot reliably subset a large CJK font again.
    pdfDoc.registerFontkit(fontkit);
    const regularShardBytes = await Promise.all(selectedRegularShards.map(async (shard) => ({
      shard,
      regular: await loadAsset(`${FONT_PATHS.shardBase}${shard.regular}`, context),
    })));
    const mediumShardBytes = await Promise.all(selectedMediumShards.map(async (shard) => ({
      shard,
      medium: await loadAsset(`${FONT_PATHS.shardBase}${shard.medium}`, context),
    })));
    const regular = [];
    const medium = [];
    for (const item of regularShardBytes) {
      const regularFont = await pdfDoc.embedFont(item.regular, { subset: false, customName: `NotoSansSC-Regular-${item.shard.index}` });
      regular.push({ font: regularFont, supported: new Set(regularFont.getCharacterSet()) });
    }
    for (const item of mediumShardBytes) {
      const mediumFont = await pdfDoc.embedFont(item.medium, { subset: false, customName: `NotoSansSC-Medium-${item.shard.index}` });
      medium.push({ font: mediumFont, supported: new Set(mediumFont.getCharacterSet()) });
    }
    const emoji = await pdfDoc.embedFont(emojiBytes, { subset: true, customName: 'NotoEmoji-Regular' });
    const emojiSupported = new Set(emoji.getCharacterSet());
    const fallbackRegular = [];
    const fallbackMedium = [];
    const regularSupported = new Set(regular.flatMap((entry) => [...entry.supported]));
    const mediumSupported = new Set(medium.flatMap((entry) => [...entry.supported]));
    // 字重分别判断缺字：正文已有常规中文字体，不代表还需要一份中等字重的日/韩回退字体。
    // 只减少未使用的字体，不对子集再次裁剪；后者在当前 fontkit 下会造成中文实际绘制空白。
    const fallbackRegularPoints = new Set([...usedCodePoints].filter((point) => !regularSupported.has(point) && !emojiSupported.has(point)));
    const fallbackMediumPoints = new Set([...mediumCodePoints].filter((point) => !mediumSupported.has(point) && !emojiSupported.has(point)));
    const shardContainsPoint = (shard, point) => Array.isArray(shard.ranges)
      ? shard.ranges.some((range) => Array.isArray(range) && point >= range[0] && point <= range[1])
      : point >= shard.start && point <= shard.end;
    const selectFallbackShards = (family, points) => (family.shards || [])
      .map((shard, index) => ({ ...shard, index }))
      .filter((shard) => [...points].some((point) => shardContainsPoint(shard, point)));
    for (const family of fallbackManifest.families) {
      const regularShards = selectFallbackShards(family, fallbackRegularPoints);
      const mediumShards = selectFallbackShards(family, fallbackMediumPoints);
      const regularBytes = await Promise.all(regularShards.map(async (shard) => ({
        shard,
        bytes: await loadAsset(`${FONT_PATHS.fallbackBase}${family.id}/${shard.regular}`, context),
      })));
      const mediumBytes = await Promise.all(mediumShards.map(async (shard) => ({
        shard,
        bytes: await loadAsset(`${FONT_PATHS.fallbackBase}${family.id}/${shard.medium}`, context),
      })));
      for (const item of regularBytes) {
        const font = await pdfDoc.embedFont(item.bytes, { subset: false, customName: `Fallback-${family.id}-Regular-${item.shard.index}` });
        fallbackRegular.push({ font, supported: new Set(font.getCharacterSet()), family: family.id });
      }
      for (const item of mediumBytes) {
        const font = await pdfDoc.embedFont(item.bytes, { subset: false, customName: `Fallback-${family.id}-Medium-${item.shard.index}` });
        fallbackMedium.push({ font, supported: new Set(font.getCharacterSet()), family: family.id });
      }
    }
    const replacementEntry = regular.find((entry) => entry.supported.has(0x25A1)) || regular[0];
    if (!replacementEntry) throw api.exportError('exportPdfNoGlyphs');
    const replacement = replacementEntry.supported.has(0x25A1) ? '□' : '?';
    const pages = [];
    const pageFontKeys = new WeakMap();
    let page = null;
    let y = contentTop;
    let currentDocumentTitle = t('exportDocumentTitle');
    let renderedSourceUrls = new Set();

    pdfDoc.setProducer('ChatGPT Tidy Export V3');
    pdfDoc.setCreator('ChatGPT Tidy');
    pdfDoc.setTitle(file.kind === 'bookmark-excerpt' ? t('exportBookmarkExcerpt') : file.conversations.map((item) => item.title).join(' / '));

    function warnOnce(message) { if (!warnings.includes(message)) warnings.push(message); }

    function clusterFont(cluster, weight = 'regular') {
      const points = [...cluster].map((character) => character.codePointAt(0));
      const ignorable = (point) => point === 0x200D || point === 0xFE0E || point === 0xFE0F;
      const primary = weight === 'medium' ? medium : regular;
      const selected = primary.find((entry) => points.every((point) => entry.supported.has(point) || ignorable(point)));
      if (selected) return { font: selected.font, text: cluster, kind: weight };
      if (points.every((point) => emojiSupported.has(point) || ignorable(point))) return { font: emoji, text: cluster, kind: 'emoji' };
      const fallbackEntry = (weight === 'medium' ? fallbackMedium : fallbackRegular)
        .find((entry) => points.every((point) => entry.supported.has(point) || ignorable(point)));
      if (fallbackEntry) return { font: fallbackEntry.font, text: cluster, kind: weight };
      warnOnce(t('exportUnsupportedGlyphs'));
      const fallback = weight === 'medium'
        ? (medium.find((entry) => entry.supported.has(replacement.codePointAt(0))) || medium[0])
        : replacementEntry;
      return { font: fallback.font, text: replacement, kind: weight };
    }

    function textRuns(value, weight = 'regular') {
      const runs = [];
      graphemes(value).forEach((cluster) => {
        const selected = clusterFont(cluster, weight);
        const previous = runs[runs.length - 1];
        if (previous?.font === selected.font && previous.kind === selected.kind) previous.text += selected.text;
        else runs.push({ ...selected });
      });
      return runs;
    }

    function runWidth(run, size) {
      try { return run.font.widthOfTextAtSize(run.text, size); }
      catch (error) {
        // Some script-specific OpenType tables make fontkit reject a whole
        // grapheme cluster even though the font can still encode and draw it.
        // Keep the original text and use per-cluster widths so it is never
        // replaced by a tofu box solely because measurement failed.
        let width = 0;
        for (const cluster of graphemes(run.text)) {
          try { width += run.font.widthOfTextAtSize(cluster, size); }
          catch (clusterError) { width += replacementEntry.font.widthOfTextAtSize(replacement, size); }
        }
        return width;
      }
    }

    function measureRuns(runs, size) { return runs.reduce((sum, run) => sum + runWidth(run, size), 0); }

    function splitRuns(value, maxWidth, size, weight = 'regular', inline = false) {
      const output = [];
      let current = [], width = 0;
      const parts = inline ? api.inlineMarkdownRuns(value) : [{ text: String(value || '') }];
      parts.forEach((part) => {
        const sourceLines = part.text.split('\n');
        sourceLines.forEach((sourceLine, lineIndex) => {
          if (lineIndex) { output.push(current); current = []; width = 0; }
          graphemes(sourceLine).forEach((cluster) => {
            const selected = { ...clusterFont(cluster, weight), url: part.url || '' };
            const selectedWidth = runWidth(selected, size);
            if (current.length && width + selectedWidth > maxWidth) { output.push(current); current = []; width = 0; }
            const previous = current[current.length - 1];
            if (previous?.font === selected.font && previous.kind === selected.kind && previous.url === selected.url) previous.text += selected.text;
            else current.push(selected);
            width += selectedWidth;
          });
        });
      });
      output.push(current);
      return output;
    }

    function addLinkAnnotation(x, bottom, width, height, url) {
      if (!/^(?:https?:|mailto:)/i.test(String(url))) return;
      try {
        // Hex strings preserve parentheses, backslashes and Unicode in URI data;
        // a raw PDF literal string can corrupt the annotation dictionary.
        const annotation = pdfDoc.context.register(pdfDoc.context.obj({
          Type: 'Annot', Subtype: 'Link', Rect: [x, bottom, x + width, bottom + height], Border: [0, 0, 0],
          A: { Type: 'Action', S: 'URI', URI: PDFHexString.fromText(String(url)) },
        }));
        page.node.addAnnot(annotation);
      } catch (error) { warnOnce(t('exportLinkAnnotationFailed')); }
    }

    function drawRunsAt(runs, x, baseline, size, color, url = '') {
      let cursor = x;
      runs.forEach((run) => {
        const width = runWidth(run, size);
        const baselineOffset = run.kind === 'emoji' ? -size * 0.08 : 0;
        if (run.text) {
          let keys = pageFontKeys.get(page);
          if (!keys) { keys = new Map(); pageFontKeys.set(page, keys); }
          let fontKey = keys.get(run.font);
          if (!fontKey) {
            fontKey = PDFLib.PDFName.of(`F${keys.size}`);
            page.node.setFontDictionary(fontKey, run.font.ref);
            keys.set(run.font, fontKey);
          }
          // PDFPage.drawText creates another random resource name on every
          // call. Mixed CJK runs can therefore create hundreds of aliases on a
          // page and some readers stop resolving them. Emit the small operator
          // sequence directly against one stable key per page and font.
          page.pushOperators(
            PDFLib.beginText(),
            PDFLib.setFillingColor(color),
            PDFLib.setFontAndSize(fontKey, size),
            PDFLib.setTextMatrix(1, 0, 0, 1, cursor, baseline + baselineOffset),
            PDFLib.showText(run.font.encodeText(run.text)),
            PDFLib.endText(),
          );
        }
        if (!url && run.url && width > 0) addLinkAnnotation(cursor, baseline - 2, width, size * 1.25, run.url);
        cursor += width;
      });
      if (url && cursor > x) addLinkAnnotation(x, baseline - 2, cursor - x, size * 1.25, url);
      return cursor - x;
    }

    function addPage() {
      page = pdfDoc.addPage();
      page.setSize(pageSize[0], pageSize[1]);
      page.drawRectangle({ x: 0, y: 0, width: pageSize[0], height: pageSize[1], color: colors.white });
      pages.push(page);
      y = contentTop;
      const headerRuns = splitRuns(currentDocumentTitle, contentWidth, 7.8)[0] || [];
      drawRunsAt(headerRuns, marginX, headerY, 7.8, colors.muted);
      page.drawLine({ start: { x: marginX, y: headerY - 7 }, end: { x: pageSize[0] - marginX, y: headerY - 7 }, thickness: 0.45, color: colors.line });
      return page;
    }

    function remainingLineCapacity(height) { return Math.max(0, Math.floor((y - footerLimit) / height)); }
    function ensureSpace(height) { if (!page) addPage(); if (y - height < footerLimit) addPage(); }
    function gap(amount = lineHeight * 0.55) { y -= amount; if (y < footerLimit) addPage(); }

    function drawWrapped(value, config = {}) {
      const size = config.size || baseSize;
      const height = config.lineHeight || size * 1.6;
      const x = config.x == null ? marginX : config.x;
      const width = config.width || contentWidth;
      const color = config.color || colors.text;
      const weight = config.weight || 'regular';
      const lines = Array.isArray(value) ? value : splitRuns(value, width, size, weight, config.inline === true);
      let index = 0;
      if (lines.length >= 4 && remainingLineCapacity(height) < 2) addPage();
      while (index < lines.length) {
        let capacity = remainingLineCapacity(height);
        if (capacity <= 0) { addPage(); capacity = remainingLineCapacity(height); }
        const remaining = lines.length - index;
        let count = Math.min(capacity, remaining);
        if (remaining > count && remaining - count === 1 && count > 1) count -= 1;
        for (let offset = 0; offset < count; offset += 1) {
          const runs = lines[index + offset];
          if (config.background) page.drawRectangle({ x: config.backgroundX ?? x - 5, y: y - height + 2, width: config.backgroundWidth || width + 10, height, color: config.background });
          drawRunsAt(runs, x, y - size, size, color, config.url || '');
          y -= height;
        }
        index += count;
        if (index < lines.length) addPage();
      }
      return lines.length * height;
    }

    function drawHeading(text, level = 2, config = {}) {
      // Process headings are source content, not document section headings.
      // Keep them at body scale so a long reasoning timeline stays calm.
      const compact = config.compact === true;
      const headingSize = compact ? baseSize : level === 1 ? baseSize * 1.58 : level === 2 ? baseSize * 1.28 : baseSize * 1.08;
      const headingLineHeight = compact ? lineHeight * 1.05 : headingSize * 1.38;
      ensureSpace(compact ? headingLineHeight * 1.8 : headingSize * 3.2);
      drawWrapped(text, { size: headingSize, lineHeight: headingLineHeight, weight: compact ? 'regular' : 'medium', color: colors.text, inline: config.inline === true });
      gap(compact ? lineHeight * 0.06 : headingSize * 0.28);
    }

    function drawSource(source, prefix = '• ') {
      if (!source?.url || renderedSourceUrls.has(source.url)) return;
      renderedSourceUrls.add(source.url);
      drawWrapped(`${prefix}${source.title || source.domain || source.url}`, { x: marginX + 8, width: contentWidth - 8, size: baseSize * 0.92, lineHeight: baseSize * 1.38, color: colors.text, url: source.url });
      drawWrapped(source.url, { x: marginX + 20, width: contentWidth - 20, size: baseSize * 0.76, lineHeight: baseSize * 1.2, color: colors.accent, url: source.url });
      gap(baseSize * 0.18);
    }

    async function drawCode(block, panelColor = colors.process) {
      const codeSize = baseSize * 0.84;
      const rowHeight = codeSize * 1.55;
      const innerX = marginX + 12;
      const innerWidth = contentWidth - 24;
      const lines = String(block.code || '').split('\n').flatMap((line) => splitRuns(line || ' ', innerWidth, codeSize));
      ensureSpace(rowHeight * Math.min(Math.max(lines.length, 2), 4) + 12);
      if (block.language) drawWrapped(block.language, { x: innerX, width: innerWidth, size: codeSize * 0.82, lineHeight: rowHeight, color: colors.muted, weight: 'medium', background: panelColor, backgroundX: marginX, backgroundWidth: contentWidth });
      for (const line of lines) {
        ensureSpace(rowHeight);
        page.drawRectangle({ x: marginX, y: y - rowHeight + 2, width: contentWidth, height: rowHeight, color: panelColor });
        drawRunsAt(line, innerX, y - codeSize, codeSize, colors.text);
        y -= rowHeight;
      }
    }

    function tableCellLines(value, width, size, weight) { return splitRuns(value, width, size, weight, true); }

    function drawTable(block) {
      const columns = Math.max(1, block.headers.length, ...block.rows.map((row) => row.length));
      const cellWidth = contentWidth / columns;
      const fontSize = baseSize * 0.78;
      const cellLineHeight = fontSize * 1.4;
      const padding = 4;
      const prepareRow = (cells, header) => {
        const lines = Array.from({ length: columns }, (_, index) => tableCellLines(cells[index] || '', Math.max(1, cellWidth - padding * 2), fontSize, header ? 'medium' : 'regular'));
        return { lines, total: Math.max(1, ...lines.map((value) => value.length)) };
      };
      const header = prepareRow(block.headers, true);
      const rows = block.rows.map((cells) => prepareRow(cells, false));
      const rowHeight = (count) => count * cellLineHeight + padding * 2;
      const availableLines = () => Math.max(0, Math.floor((y - footerLimit - padding * 2) / cellLineHeight));
      const fullPageHeight = contentTop - footerLimit;
      const headerHeight = rowHeight(header.total);
      // 排版规则：能放在新页的一整行绝不拆；新页容量必须扣掉重复表头和单元格留白。
      // 极端长表头若占满一页，则完整绘制一次，后续页不重复它，确保正文总能继续。
      const repeatHeader = headerHeight + rowHeight(1) <= fullPageHeight;
      const freshRowCapacity = Math.max(1, Math.floor((fullPageHeight - (repeatHeader ? headerHeight : 0) - padding * 2) / cellLineHeight));
      const renderChunk = (row, isHeader, startLine, lineCount) => {
        const height = rowHeight(lineCount);
        page.drawRectangle({ x: marginX, y: y - height, width: contentWidth, height, color: isHeader ? colors.process : colors.white, borderColor: colors.line, borderWidth: 0.6 });
        row.lines.forEach((lines, column) => {
          const x = marginX + column * cellWidth;
          if (column) page.drawLine({ start: { x, y }, end: { x, y: y - height }, thickness: 0.6, color: colors.line });
          lines.slice(startLine, startLine + lineCount).forEach((runs, lineIndex) => drawRunsAt(runs, x + padding, y - padding - fontSize - lineIndex * cellLineHeight, fontSize, isHeader ? colors.text : colors.muted));
        });
        y -= height;
      };
      const nextTablePage = () => {
        addPage();
        if (repeatHeader) renderChunk(header, true, 0, header.total);
      };
      if (repeatHeader) {
        const firstRowLines = rows.length ? Math.min(rows[0].total, freshRowCapacity) : 0;
        ensureSpace(headerHeight + (firstRowLines ? rowHeight(firstRowLines) : 0));
        renderChunk(header, true, 0, header.total);
      } else {
        let start = 0;
        while (start < header.total) {
          if (!availableLines()) addPage();
          const count = Math.min(header.total - start, availableLines());
          renderChunk(header, true, start, count);
          start += count;
        }
      }
      rows.forEach((row) => {
        let start = 0;
        // 只有超过“整页减表头”容量的长行才允许跨页；普通行整体移到下一页。
        if (row.total <= freshRowCapacity && availableLines() < row.total) nextTablePage();
        while (start < row.total) {
          if (!availableLines()) nextTablePage();
          const count = Math.min(row.total - start, availableLines());
          renderChunk(row, false, start, count);
          start += count;
          if (start < row.total) nextTablePage();
        }
      });
    }

    async function drawImage(block, resourcesById) {
      const resource = resourcesById.get(block.resourceId);
      const alt = block.alt || resource?.alt || resource?.name || t('exportImage');
      if (!resource?.src) { drawWrapped(`［${t('exportImageLabel', { name: alt })}］`, { color: colors.muted, size: baseSize * 0.9 }); warnOnce(t('exportImageNoAddress', { name: alt })); return; }
      try {
        const bytes = await loadAsset(resource.src, context);
        const prepared = await preparePdfImage(bytes);
        const image = await (prepared.format === 'jpeg' ? pdfDoc.embedJpg(prepared.bytes) : pdfDoc.embedPng(prepared.bytes));
        const maxWidth = Math.min(contentWidth, 430);
        const maxHeight = contentTop - footerLimit - lineHeight * 2;
        const ratio = Math.min(1, maxWidth / image.width, maxHeight / image.height);
        const width = image.width * ratio;
        const height = image.height * ratio;
        ensureSpace(height + lineHeight * 1.5);
        const x = marginX + (contentWidth - width) / 2;
        page.drawImage(image, { x, y: y - height, width, height });
        if (!resource.temporaryUrl && /^https?:\/\//i.test(resource.src)) addLinkAnnotation(x, y - height, width, height, resource.src);
        y -= height + 4;
        drawWrapped(alt, { x, width, size: baseSize * 0.8, lineHeight: baseSize * 1.2, color: colors.muted });
      } catch (error) { drawWrapped(`［${t('exportImageEmbedFailed', { name: alt })}］`, { color: colors.muted, size: baseSize * 0.9 }); warnOnce(t('exportImageEmbedFailed', { name: alt })); }
    }

    function drawAttachment(block, resourcesById, sourceUrl) {
      const card = api.attachmentPresentation(block, { messages: context.messages, resourcesById, sourceUrl });
      const innerWidth = contentWidth - 24;
      const title = t('exportAttachment') + ' · ' + card.name;
      const titleLines = splitRuns(title, innerWidth, baseSize * 0.94, 'medium');
      const detailLines = card.details ? splitRuns(card.details, innerWidth, baseSize * 0.78) : [];
      // 无交付说明的短卡片维持原尺寸；长文件名也必须测量后换行，不能画出纸外。
      if (!block.label?.trim() && titleLines.length === 1 && detailLines.length <= 1) {
        const height = card.details ? lineHeight * 2.35 : lineHeight * 1.65;
        ensureSpace(height + 4);
        page.drawRectangle({ x: marginX, y: y - height, width: contentWidth, height, color: colors.user, borderColor: colors.line, borderWidth: 0.6 });
        drawRunsAt(titleLines[0], marginX + 12, y - baseSize * 1.22, baseSize * 0.94, colors.text);
        if (card.details) drawRunsAt(detailLines[0], marginX + 12, y - lineHeight - baseSize * 1.05, baseSize * 0.78, colors.muted);
        y -= height;
        return;
      }
      // 卡片按实际字形宽度排版。可放进一页时整体移动；超长说明按行续页，
      // 每行只绘制一次，来源明确为原会话，不把 sandbox 路径伪装成下载地址。
      const rows = [];
      const append = (lines, size, height, color, url = '') => lines.forEach(runs => rows.push({ runs, size, height, color, url }));
      append(titleLines, baseSize * 0.94, lineHeight, colors.text);
      append(detailLines, baseSize * 0.78, lineHeight * 0.85, colors.muted);
      if (card.label) append(splitRuns(card.label, innerWidth, baseSize * 0.86), baseSize * 0.86, lineHeight * 0.92, colors.muted);
      if (card.sourceUrl) append(splitRuns(t('exportOpenOriginal'), innerWidth, baseSize * 0.8), baseSize * 0.8, lineHeight * 0.88, colors.accent, card.sourceUrl);
      const padding = 8;
      const fullHeight = rows.reduce((sum, row) => sum + row.height, padding * 2);
      if (fullHeight <= contentTop - footerLimit) ensureSpace(fullHeight);
      let index = 0;
      while (index < rows.length) {
        ensureSpace(padding * 2 + rows[index].height);
        let end = index, height = padding * 2;
        while (end < rows.length && height + rows[end].height <= y - footerLimit) height += rows[end++].height;
        const top = y;
        page.drawRectangle({ x: marginX, y: top - height, width: contentWidth, height, color: colors.user, borderColor: colors.line, borderWidth: 0.6 });
        y -= padding;
        while (index < end) {
          const row = rows[index++];
          drawRunsAt(row.runs, marginX + 12, y - row.size, row.size, row.color, row.url);
          y -= row.height;
        }
        y = top - height;
        if (index < rows.length) addPage();
      }
    }

    async function drawBlocks(blocks, resourcesById, config = {}) {
      for (const block of blocks || []) {
        if (block.type === 'paragraph') drawWrapped(block.text, { ...config.text, inline: true });
        else if (block.type === 'heading') drawHeading(block.text, block.level, { ...config.heading, inline: true });
        else if (block.type === 'unordered-list' || block.type === 'ordered-list') block.items.forEach((item, index) => drawWrapped(`${block.type === 'ordered-list' ? `${index + 1}.` : '•'} ${item}`, { x: marginX + 12, width: contentWidth - 12, ...(config.text || {}), inline: true }));
        else if (block.type === 'blockquote') {
          const startY = y;
          drawWrapped(block.text, { x: marginX + 16, width: contentWidth - 22, color: colors.muted, ...(config.text || {}), inline: true });
          page.drawRectangle({ x: marginX + 4, y: y + 2, width: 2, height: Math.max(8, startY - y), color: colors.accent });
        } else if (block.type === 'code') await drawCode(block, config.panelColor || colors.process);
        else if (block.type === 'table') drawTable(block);
        else if (block.type === 'image') await drawImage(block, resourcesById);
        else if (block.type === 'attachment') drawAttachment(block, resourcesById, config.sourceUrl);
        else if (block.type === 'link') drawWrapped(api.plainLinkText(api.inlinePlainText(block.text), block.url), { color: colors.accent, url: block.url });
        gap(lineHeight * 0.28);
      }
    }

    function processCategoryLabel(category) {
      return api.processCategoryLabel(category, context.messages);
    }

    function processSubLabel(segment) {
      const label = String(segment?.label || '').trim();
      return label && label !== processCategoryLabel(segment?.category) ? label : '';
    }

    async function drawProcessGroup(group, resourcesById, sourceUrl) {
      ensureSpace(lineHeight * 2.5);
      const panelText = { x: marginX + 10, width: contentWidth - 20, color: colors.muted, background: colors.process, backgroundX: marginX, backgroundWidth: contentWidth };
      drawWrapped(processCategoryLabel(group.category), { ...panelText, size: baseSize * 0.9, lineHeight: lineHeight * 0.92, color: colors.accent, weight: 'medium' });
      for (const segment of group.segments) {
        const subLabel = processSubLabel(segment);
        if (subLabel) drawWrapped(subLabel, { ...panelText, size: baseSize * 0.92, lineHeight: lineHeight * 0.98, color: colors.text, weight: 'regular' });
        if (segment.tool?.name) drawWrapped(t('exportToolLabel', { name: segment.tool.name }), { ...panelText, size: baseSize * 0.82 });
        await drawBlocks(segment.blocks, resourcesById, { sourceUrl, panelColor: colors.process, text: panelText, heading: { compact: group.category === 'reasoning' } });
        segment.queries?.forEach((query) => drawWrapped(t('exportQueryLabel', { query }), { ...panelText, size: baseSize * 0.86 }));
        segment.results?.forEach((source) => drawSource(source));
      }
      gap(lineHeight * 0.22);
    }

    async function drawSegment(segment, resourcesById, sourceUrl) {
      if (segment.type === 'content') await drawBlocks(segment.blocks, resourcesById, { sourceUrl });
      else if (segment.type === 'process') await drawProcessGroup({ type: 'process-group', category: segment.category, segments: [segment] }, resourcesById, sourceUrl);
      else if (segment.type === 'process-group') await drawProcessGroup(segment, resourcesById, sourceUrl);
      else if (segment.type === 'sources') {
        const unseen = segment.items.filter((source) => !renderedSourceUrls.has(source.url));
        if (!unseen.length) return;
        drawHeading(t('exportFinalSources'), 3);
        unseen.forEach((source) => drawSource(source));
      }
    }

    async function drawMessage(message, conversation, groupName = '') {
      const resourcesById = new Map((conversation.resources || []).map((resource) => [resource.id, resource]));
      const meta = [];
      if (options.messageNumbers) meta.push(`#${message.messageNumber}`);
      if (options.timestamps && message.timestamp) meta.push(typeof context.formatTimestamp === 'function' ? context.formatTimestamp(message.timestamp) : message.timestamp);
      const label = `${api.roleName(message, context.roleNames)}${meta.length ? `  ${meta.join('  ')}` : ''}`;
      ensureSpace(lineHeight * 3.1);
      drawWrapped(label, { size: baseSize * 0.96, lineHeight: lineHeight * 1.05, color: colors.accent, weight: 'medium', ...(message.role === 'user' ? { background: colors.user, backgroundX: marginX, backgroundWidth: contentWidth } : {}) });
      gap(lineHeight * 0.18);
      const segments = typeof api.groupAdjacentProcessSegments === 'function'
        ? api.groupAdjacentProcessSegments(message.segments)
        : message.segments;
      for (const segment of segments) await drawSegment(segment, resourcesById, conversation.sourceUrl);
      if (groupName) drawWrapped(t('exportFromGroup', { name: groupName }), { size: baseSize * 0.78, lineHeight: baseSize * 1.25, color: colors.muted });
      gap(lineHeight * 0.42);
      ensureSpace(3);
      page.drawLine({ start: { x: marginX, y }, end: { x: pageSize[0] - marginX, y }, thickness: 0.5, color: colors.line });
      gap(lineHeight * 0.62);
    }

    async function drawConversation(conversation, messages = conversation.messages, groupsByMessage = new Map()) {
      currentDocumentTitle = conversation.title;
      renderedSourceUrls = new Set();
      if (!page) addPage();
      drawHeading(conversation.title, 1);
      if (options.timestamps) {
        const start = typeof context.formatTimestamp === 'function' ? context.formatTimestamp(conversation.createdAt) : conversation.createdAt;
        const end = typeof context.formatTimestamp === 'function' ? context.formatTimestamp(conversation.updatedAt) : conversation.updatedAt;
        drawWrapped(`${start} ～ ${end}`, { size: baseSize * 0.8, lineHeight: baseSize * 1.25, color: colors.muted });
      }
      if (conversation.sourceUrl) drawWrapped(conversation.sourceUrl, { size: baseSize * 0.76, lineHeight: baseSize * 1.2, color: colors.accent, url: conversation.sourceUrl });
      gap(lineHeight * 0.62);
      for (const message of messages) await drawMessage(message, conversation, groupsByMessage.get(message.id));
    }

    if (file.kind === 'conversation') {
      for (let index = 0; index < file.conversations.length; index += 1) { if (index) addPage(); await drawConversation(file.conversations[index]); }
    } else {
      currentDocumentTitle = t('exportBookmarkExcerpt');
      addPage();
      drawHeading(t('exportBookmarkExcerpt'), 1);
      drawWrapped(t('exportExcerptNotice'), { color: colors.muted });
      gap(lineHeight * 0.8);
      for (const conversation of api.bookmarkConversations(file)) {
        if (y < pageSize[1] * 0.35) addPage();
        const groups = new Map(conversation.entries.map((entry) => [entry.message.id, entry.groupName]));
        await drawConversation(conversation, conversation.entries.map((entry) => entry.message), groups);
      }
    }

    pages.forEach((targetPage, index) => {
      if (!pdfOptions.pageNumbers) return;
      const runs = textRuns(`${index + 1} / ${pages.length}`);
      const width = measureRuns(runs, 8);
      const previous = page;
      page = targetPage;
      drawRunsAt(runs, (pageSize[0] - width) / 2, 18, 8, colors.muted);
      page = previous;
    });

    const bytes = await pdfDoc.save({ useObjectStreams: false });
    return { bytes, warnings, pageCount: pages.length, pageSize };
  }

  Object.assign(api, { PAGE_SIZES, FONT_SIZES, FONT_PATHS, preparePdfImage, serializePdf });
}(typeof globalThis !== 'undefined' ? globalThis : window));
